version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'cocon-material' # give your contatner a name
    environment:
      - MONGO_INITDB_DATABASE=sample
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'

