version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: /usr/local/wait-for-it.sh mongo:27017 -- npm start
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - material-net
    depends_on:
      - database

  database:
    image: 'mongo'
    container_name: 'cocon-material'
    environment:
      - MONGO_INITDB_DATABASE=sample
    volumes:
      - ./mongo-volume:/data/db
    networks:
      - material-net
    ports:
      - '27017-27019:27017-27019'

networks:
  material-net:
